### ISSUE TITLE
Extra OMF Relocation Data

### ISSUE THREAD

**Issue by dwsJason** [lroathe/merlin32#5]
I have a code segment, with code like this:

`  491 |  1             devmenu.s    446 | Data        | 00 |  2      |    8 | 00/01E4 : 26 02 11 04 |                       da       _txt_play_game,do_playgame,{0},{0}
`
`      |                                 |             |    |         |      |           00 00 00 00 |
`

both locations that should contain zero, get relocated to  do_playgame, a local label in the segment,  so instead of the code generated above, I get:

01E4: 26 02 11 04 11 04 11 04

**Comment by dwsJason** [comment]
[asm.zip](https://github.com/lroathe/merlin32/files/5296077/asm.zip)

if you look at omfdump, offset $19, you can see 2 extra relocates in the relocation dictionary, at $1B, and $1D

merlin32 -v . link.s  - to rebuild

**Comment by digarok** [comment]
Confirmed this happens on OSX with release 1.1.9.

Seems to be a parsing/buffer bug that puts repeated junk in the subsequent zero words.  

As a workaround, you can try splitting up the lines to not put the relocatable entries on the same line as the literal values like:
```
        da  start,End
        da  0,0
```

This seems to build correctly.

**Comment by dwsJason** [comment]
Pull Request to fix the issue is posted

**Comment by digarok** [comment]
@dwsJason I'm submitting my alternate fix which revert to initializing the value upfront.   https://github.com/lroathe/merlin32/pull/7

**Comment by lroathe** [comment]
Closing, fixed in pull request #7
